name: learn-github-actions

on: [push]
jobs:
  learn-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: | 
               npm install
               npm run test
      - run: npm run coverage

      - uses: actions/upload-artifact@v3
        with:
           name: my-artifact
           path: /home/runner/work/Acarin-node.js/Acarin-node.js/
