# This is a basic workflow to help you get started with Actions

name: sample CI pipeline

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yml
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.call-build-test.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.call-build-test.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
